apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: dfloo-profile-api
  namespace: dfloo-profile
spec:
  selector:
    matchLabels:
      app: dfloo-profile-api
  endpoints:
    - port: 8080
      path: /metrics
      interval: 120s
      metricRelabeling:
        - action: drop
          sourceLabels:
            - __name__
          regex: go_.*|process_.*|promhttp_.*|http_.*
        - action: labeldrop
          regex: uid|pod_uid|container_id|image_id
