services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
     - dfloo-network
    volumes:
     - .:/app
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
     - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data
    networks:
     - dfloo-network
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
     - dfloo-network
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    volumes:
     - ./db/migrations:/migrations
    entrypoint: [ "sh", "-c", "migrate -path /migrations -database \"$$DATABASE_URL\" up" ]

networks:
  dfloo-network:
volumes:
  postgres-data:
