services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
     - dfloo-network
    volumes:
     - .:/app
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
     - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data
    networks:
     - dfloo-network
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
     - dfloo-network
    environment:
      DATABASE_URL: "postgres://${PGUSER}:${PGPASSWORD}@postgres:5432/${PGDATABASE}?sslmode=disable"
    volumes:
     - ./db/migrations:/migrations
    entrypoint: [ "sh", "-c", "migrate -path /migrations -database \"$$DATABASE_URL\" up" ]
  f1-loader:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["seed"]
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
     - dfloo-network
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
    command: ["/dfloo-f1-loader", "--data-dir", "/db/f1-data"]

networks:
  dfloo-network:
volumes:
  postgres-data:
