apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets-provider
  namespace: dfloo-profile
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/dfloo-profile/secrets/POSTGRES_DB/versions/latest"
        path: "postgres-db"
      - resourceName: "projects/dfloo-profile/secrets/POSTGRES_USER/versions/latest"
        path: "postgres-user"
      - resourceName: "projects/dfloo-profile/secrets/POSTGRES_PASSWORD/versions/latest"
        path: "postgres-password"
      - resourceName: "projects/dfloo-profile/secrets/SQL_INSTANCE_CONNECTION_NAME/versions/latest"
        path: "sql-instance-connection-name"
      - resourceName: "projects/dfloo-profile/secrets/RESEND_API_KEY/versions/latest"
        path: "resend-api-key"
      - resourceName: "projects/dfloo-profile/secrets/ANTHROPIC_API_KEY/versions/latest"
        path: "anthropic-api-key"
