apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets-provider
  namespace: dfloo-profile
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/dfloo-profile/secrets/POSTGRES_DB/versions/latest"
        path: "postgres-db"
      - resourceName: "projects/dfloo-profile/secrets/POSTGRES_USER/versions/latest"
        path: "postgres-user"
      - resourceName: "projects/dfloo-profile/secrets/POSTGRES_PASSWORD/versions/latest"
        path: "postgres-password"
      - resourceName: "projects/dfloo-profile/secrets/SQL_INSTANCE_CONNECTION_NAME/versions/latest"
        path: "sql-instance-connection-name"
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - key: POSTGRES_DB
          objectName: postgres-db
        - key: POSTGRES_USER
          objectName: postgres-user
        - key: POSTGRES_PASSWORD
          objectName: postgres-password
        - key: SQL_INSTANCE_CONNECTION_NAME
          objectName: sql-instance-connection-name
