apiVersion: v1
kind: ServiceAccount
metadata:
  name: dfloo-profile-k8s
  namespace: dfloo-profile
  annotations:
    iam.gke.io/gcp-service-account: dfloo-profile-k8s@dfloo-profile.iam.gserviceaccount.com
